/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.DataStreamService;

import java.net.URISyntaxException;

public class App {
    public static void main(String[] args) throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("input.txt");
        System.out.println("Result : " + dataStreamService.getMarkerComplete());
    }
}
