/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.DataStreamService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.net.URISyntaxException;

class DataStreamServiceTest {


    @Test
    void considerTestOneResultShouldBe7and10() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-one.txt");
        Assertions.assertEquals(7, dataStreamService.getStartOfPacketMarkerComplete());
        Assertions.assertEquals(19, dataStreamService.getMessageMarkerComplete());
    }

    @Test
    void considerTestTwoResultShouldBe7and23() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-two.txt");
        Assertions.assertEquals(7, dataStreamService.getStartOfPacketMarkerComplete());
        Assertions.assertEquals(23, dataStreamService.getMessageMarkerComplete());
    }

    @Test
    void considerTestThreeResultShouldBe6and23() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-three.txt");
        Assertions.assertEquals(6, dataStreamService.getStartOfPacketMarkerComplete());
        Assertions.assertEquals(23, dataStreamService.getMessageMarkerComplete());
    }

    @Test
    void considerTestFourResultShouldBe11and29() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-four.txt");
        Assertions.assertEquals(11, dataStreamService.getStartOfPacketMarkerComplete());
        Assertions.assertEquals(29, dataStreamService.getMessageMarkerComplete());
    }

    @Test
    void considerTestFiveResultShouldBe11and26() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-five.txt");
        Assertions.assertEquals(11, dataStreamService.getStartOfPacketMarkerComplete());
        Assertions.assertEquals(26, dataStreamService.getMessageMarkerComplete());
    }
}
