/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.DataStreamService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.net.URISyntaxException;

class DataStreamServiceTest {


    @Test
    void considerTestOneResultShouldBe7() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-one.txt");
        Assertions.assertEquals(7, dataStreamService.getMarkerComplete());
    }

    @Test
    void considerTestTwoResultShouldBe5() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-two.txt");
        Assertions.assertEquals(5, dataStreamService.getMarkerComplete());
    }

    @Test
    void considerTestThreeResultShouldBe6() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-three.txt");
        Assertions.assertEquals(6, dataStreamService.getMarkerComplete());
    }

    @Test
    void considerTestFourResultShouldBe10() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-four.txt");
        Assertions.assertEquals(10, dataStreamService.getMarkerComplete());
    }

    @Test
    void considerTestFiveResultShouldBe11() throws URISyntaxException {
        DataStreamService dataStreamService = new DataStreamService("test-five.txt");
        Assertions.assertEquals(11, dataStreamService.getMarkerComplete());
    }
}
