/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

public class App {

    public static void main(String[] args) {
        System.out.println("Ready for Day 3... Are you?");
    }
}
