/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.RucksackService;
import java.net.URISyntaxException;

public class App {

    public static void main(String[] args) throws URISyntaxException {
        RucksackService rucksackService = new RucksackService("input.txt");
        System.out.println("Sum of priorities for matching items: " + rucksackService.getScore());
        System.out.println("Sum of priorities for each group: " + rucksackService.getGroupScore());
    }
}
