/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import java.io.File;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Scanner;

public class App {

    static int oneCal = 0;
    static int twoCal = 0;
    static int threeCal = 0;

    static int currentCalories = 0;
    public static void main(String[] args) throws URISyntaxException {
        File input = getFile();

        try (Scanner scanner = new Scanner(input)) {
            while(scanner.hasNext()) {
                String line = scanner.nextLine();
                if (line.isEmpty()) {
                    checkCurrentElfSnacks();
                } else {
                    currentCalories += Integer.parseInt(line);
                }
            }
        } catch (Exception ex) {
            // Whoops :D
        }
        int total = oneCal + twoCal + threeCal;
        System.out.println("Most Calories on an Elf: " + oneCal);
        System.out.println("Total Calories on top 3 Elves: " + total);
    }

    private static void checkCurrentElfSnacks() {
        if (currentCalories > oneCal) {
            threeCal = twoCal;
            twoCal = oneCal;
            oneCal = currentCalories;
        } else if (currentCalories > twoCal) {
            threeCal = twoCal;
            twoCal = currentCalories;
        } else if (currentCalories > threeCal) {
            threeCal = currentCalories;
        }

        currentCalories = 0;
    }

    private static File getFile() throws URISyntaxException {
        URL resource = App.class.getClassLoader().getResource("input.txt");
        if (resource == null) {
            throw new IllegalArgumentException("Resource " + "input.txt" + " is missing...");
        } else {
            return new File(resource.toURI());
        }
    }
}
