/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.CraneService;

import java.net.URISyntaxException;

public class App {
    public static void main(String[] args) throws URISyntaxException {
        CraneService craneService = new CraneService("input.txt");
        System.out.println("Top crates are : " + craneService.getTopCrates());
    }
}
