/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.GameService;
import com.xfrenzy47x.aoc.service.NewGameService;
import com.xfrenzy47x.aoc.util.Helper;

import java.io.File;
import java.net.URISyntaxException;

public class App {

    public static void main(String[] args) throws URISyntaxException {
        File input = Helper.getFile("input.txt");

        GameService gameService = new GameService(input);
        NewGameService newGameService = new NewGameService(input);

        System.out.println("My score following the old rules are: " + gameService.getScore());
        System.out.println("My score following the new rules are: " + newGameService.getScore());
    }


}
