/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.CleanupService;

import java.net.URISyntaxException;

public class App {
    public static void main(String[] args) throws URISyntaxException {
        CleanupService cleanupService = new CleanupService("input.txt");
        System.out.println("Number of full contained is: " + cleanupService.getFullyContainScore());
        System.out.println("Number of overlap is: " + cleanupService.getOverlapScore());
    }
}
