/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.CleanupService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.net.URISyntaxException;

class CleanupServiceTest {
    @Test
    void withTestDataFullyContainScoreShouldBe2() throws URISyntaxException {
        CleanupService cleanupService = new CleanupService("input.txt");
        Assertions.assertEquals(2, cleanupService.getFullyContainScore());
    }

    @Test
    void withTestDataOverlapScoreShouldBe4() throws URISyntaxException {
        CleanupService cleanupService = new CleanupService("input.txt");
        Assertions.assertEquals(4, cleanupService.getOverlapScore());
    }
}
