/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.CraneService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.net.URISyntaxException;

class CraneServiceTest {
    @Test
    void consideringTestDataTopStackWillBeCMZ() throws URISyntaxException {
        CraneService craneService = new CraneService("input.txt");
        Assertions.assertEquals("CMZ", craneService.getTopCrates());
    }
}
