/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xfrenzy47x.aoc;

import com.xfrenzy47x.aoc.service.UpdatedCraneService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.net.URISyntaxException;

class UpdatedCraneServiceTest {
    @Test
    void consideringTestDataTopStackWillBeMCD() throws URISyntaxException {
        UpdatedCraneService updatedCraneService = new UpdatedCraneService("input.txt");
        Assertions.assertEquals("MCD", updatedCraneService.getTopCrates());
    }
}
